//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PendientesProveedores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONVENIOS_UTILITY
    {
        public int CONVENIO_UTILITY_ID { get; set; }
        public int UTILITY_ID { get; set; }
        public int NUMERO_CONVENIO { get; set; }
        public int PRODUCTO_ID { get; set; }
        public string ALIAS_CONVENIO { get; set; }
        public Nullable<bool> ACTIVO_VENTAS { get; set; }
        public Nullable<int> LOCAL_GRUPO_CONVENIO { get; set; }
        public Nullable<int> LOCAL_TIPO_PRODUCTO { get; set; }
    }
}
