//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PendientesProveedores.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Globalization;
    using System.Web.Mvc;
    
    public partial class Local_Pendientes_Proveedores
    {
        [Required(ErrorMessage = "Debe Introducir una fecha")]
        [DataType(DataType.Date, ErrorMessage = "Debe ser una fecha que sea valida")]
        [DisplayFormat(DataFormatString = "{0:dd-MMM-yyyy}", ApplyFormatInEditMode = true)]
        public System.DateTime FECHA { get; set; }
        public string formatoFecha
        {
            get
            {
                return FECHA.ToShortDateString();
            }
        }

        public int UTILITY_ID { get; set; }

        [Required(ErrorMessage = "Debe Introducir un monto para Pendiente de Pago")]
        [RegularExpression(@"\d+(\.\d{1,2})?", ErrorMessage = "Formato de monto inválido")]
        public decimal PENDIENTE_PAGO { get; set; }

        [Required(ErrorMessage = "Debe Introducir un monto para Pendiente de Cobro")]
        [RegularExpression(@"\d+(\.\d{1,2})?", ErrorMessage = "Formato de monto inválido")]
        public decimal PENDIENTE_COBRO { get; set; }
        public string ESTADO { get; set; }
        public int Pendiente_proveedor_id { get; set; }

        [NotMapped]
        public string proveedorSeleccionado { get; set; }
        [NotMapped]
        public SelectList listaProveedores { get; set; }
    }
}
