//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PendientesProveedores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Local_Pendientes_Proveedores
    {
        public System.DateTime FECHA { get; set; }
        public int UTILITY_ID { get; set; }
        public decimal PENDIENTE_PAGO { get; set; }
        public decimal PENDIENTE_COBRO { get; set; }
        public string ESTADO { get; set; }
        public int Pendiente_proveedor_id { get; set; }
    }
}
