//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PendientesProveedores.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UTILITIES
    {
        public Nullable<int> UTILITY_ID { get; set; }
        public Nullable<int> CODIGO_UTILITY { get; set; }
        public string RAZON_SOCIAL { get; set; }
        public string GIRO_COMERCIAL { get; set; }
        public Nullable<int> RUT { get; set; }
        public string DV_RUT { get; set; }
        public string FONOS { get; set; }
        public string FAX { get; set; }
        public string COMUNA_CODE { get; set; }
        public string CIUDAD_CODE { get; set; }
        public string REGION_CODE { get; set; }
        public string CALLE { get; set; }
        public string NUMERO_DIR { get; set; }
        public string DEPTO_DIR { get; set; }
        public string CODIGO_POSTAL { get; set; }
        public string SITIO_INTERNET { get; set; }
        public string CORREO_ELECTRONICO { get; set; }
        public Nullable<int> CUENTA_SUN { get; set; }
    }
}
