//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PendientesProveedores.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VIA_DREntities : DbContext
    {
        public VIA_DREntities()
            : base("name=VIA_DREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Local_Grupo_Convenio> Local_Grupo_Convenio { get; set; }
        public virtual DbSet<Local_Pendientes_Proveedores> Local_Pendientes_Proveedores { get; set; }
        public virtual DbSet<UTILITIES> UTILITIES { get; set; }
        public virtual DbSet<CONVENIOS_UTILITY> CONVENIOS_UTILITY { get; set; }
    }
}
